FILE_EXCEL_DATA = "data.xlsx"

SHEET_INFO = "info"
SHEET_TEACHER_INFO = "teacher_hours"
SHEET_CLASS_TEACHERS_INFO = "class_teachers"
SHEET_COURSE_HOURS_INFO = "course_hours"

COURSES = ['1ESO', '2ESO', '3ESO', '4ESO', '1BATX', '2BATX']

DAYS_PER_WEEK = 5
WEEK_DAYS = ['LUNES', 'MARTES', 'MIÉRCOLES', 'JUEVES', 'VIERNES']

HOURS_PER_DAY = 7
HOUR_START_DAY = 8
HOUR_END_DAY = 15

TIME_SLOTS = HOURS_PER_DAY * DAYS_PER_WEEK

MAXIMUM_GENERATIONS = 50
TOTAL_PARENTS = 10

BASE = 1.5

HCW = 1000
SCW = 5

POPULATION_SIZE = 20
DESCENDANTS = 10