FILE_EXCEL_DATA = "data.xlsx"

SHEET_INFO = "info"
SHEET_TEACHER_INFO = "teacher_hours"
SHEET_CLASS_TEACHERS_INFO = "class_teachers"
SHEET_COURSE_HOURS_INFO = "course_hours"

DAYS_PER_WEEK = 5
WEEK_DAYS = ['LUNES', 'MARTES', 'MIÉRCOLES', 'JUEVES', 'VIERNES']

HOURS_PER_DAY = 7
HOUR_START_DAY = 8
HOUR_END_DAY = 15

MAXIMUM_GENERATIONS = 100
